spring:
  data:
    mongodb:
      uri: mongodb+srv://himadri_das:himadridas24@cluster0.8vastty.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

  main:
    allow-circular-references: true

server:
  servlet:
    context-path: /journal
  port: 8081